version: "3"
services:
  acedatacloud-facilitator-backend:
    platform: linux/amd64
    container_name: "acedatacloud-facilitator-backend"
    build: ./
    image: "ghcr.io/acedatacloud/facilitator-backend:${BUILD_NUMBER}"
    ports:
      - "8008:8000"
    command: ["uvicorn", "core.asgi:application", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - .env
