version: "3"
services:
  acedatacloud-platform-facilitator:
    platform: linux/amd64
    container_name: "acedatacloud-platform-facilitator"
    build: ./
    image: "ghcr.io/acedatacloud/platform-facilitator:${BUILD_NUMBER}"
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      APP_ENV: "local"
    command: ["uvicorn", "core.asgi:application", "--host", "0.0.0.0", "--port", "8000"]
